// tests/cv-quality-gates-i18n.test.mjs — both CV quality gates must work on a
// CV the tool itself generated in a non-English language.
//
// THE BUG THIS PINS. Both gates were written against English word lists, and
// AGENTS.md makes non-English output first-class (`language.output` governs
// "reports, tracker notes, PDFs, cover letters ... any user-visible prose",
// and modes/ ships eighteen market mode sets). On a German CV generated by
// this repo's own pdf mode:
//
//   verify-cv-facts  all six count claims ("15 Jahren Erfahrung", "6 Commercial
//                    Project Managern", "22 Mitarbeitenden", ...) came back
//                    unread, so the hard fact gate verified ZERO counts and
//                    emitted only a warning. The claims happened to be true;
//                    the gate provided no protection either way.
//   verify-ats       "[critical] Missing standard section heading(s):
//                    Experience, Education, Skills" against Berufserfahrung /
//                    Ausbildung / Kenntnisse — the correct German headings,
//                    emitted by build-cv-html.mjs's own documented `sections`
//                    payload field. 65/100, below the 70 threshold, almost
//                    entirely from that one false positive.
//
// WHY IT BUILDS THE HTML RATHER THAN SHIPPING IT. The fixtures are payloads,
// rendered through build-cv-html.mjs here, so what the gates see is the real
// template — the actual `section-title` markup, the `var(--font-family)` stacks,
// the CSS comment containing a literal "<img>". A checked-in HTML fixture would
// drift from the template and stop testing the thing that broke.
//
// Japanese is the second fixture because CJK breaks differently from German,
// not merely more: its headings share no Latin stem at all, its counts sit
// flush against the surrounding text ("3拠点で45名") so no word boundary
// applies, its dates ARE count claims ("2024年"), and it states the same
// content in a third of the characters, which trips checks that count them.
//
// Arabic is the third because it is RTL and writes its numbers in Arabic-Indic
// digits (٢٢, ١٨٪). Those have to fold to ASCII AND resolve against the noun
// lexicon for a count to be checked at all, and only this fixture exercises the
// two together through the real builder.
//
// Run:  node --test tests/cv-quality-gates-i18n.test.mjs

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { auditAts, isPass, DEFAULT_MIN_SCORE } from '../verify-ats.mjs';
import { verifyFacts, metricClaims } from '../verify-cv-facts.mjs';
import { METRIC_NOUN_FORMS, SUPPORTED_LANGUAGES, metricNounIndex } from '../cv-lexicons.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FIXTURES = join(ROOT, 'tests', 'fixtures');

/** Render a fixture payload through the real CV builder and return its HTML. */
function buildCv(lang) {
  const dir = mkdtempSync(join(tmpdir(), `cv-i18n-${lang}-`));
  try {
    const out = join(dir, `cv-${lang}.html`);
    const res = spawnSync(
      process.execPath,
      ['build-cv-html.mjs', join(FIXTURES, `cv-payload-${lang}.json`), out],
      { cwd: ROOT, encoding: 'utf-8' },
    );
    assert.equal(res.status, 0, `build-cv-html.mjs failed for ${lang}: ${res.stderr || res.stdout}`);
    return readFileSync(out, 'utf-8');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const factsFor = (html, lang) => verifyFacts(html, {
  sourcePaths: [join('tests', 'fixtures', `cv-source-${lang}.md`)],
  configPath: 'config/__no_such_config__.json',
  cwd: ROOT,
});

// ── verify-ats ───────────────────────────────────────────────────────

for (const [lang, headings] of [
  ['de', ['Berufserfahrung', 'Ausbildung', 'Kenntnisse']],
  ['ja', ['職務経歴', '学歴', 'スキル']],
  ['ar', ['الخبرة المهنية', 'التعليم', 'المهارات']],
]) {
  test(`verify-ats accepts the ${lang} section headings the builder emits`, () => {
    const html = buildCv(lang);
    for (const heading of headings) {
      assert.ok(html.includes(heading), `fixture regression: ${heading} is not in the generated HTML`);
    }

    const result = auditAts(html);
    const missing = result.issues.filter(i => /Missing standard section heading/.test(i.message));
    assert.deepEqual(missing, [], `${lang}: correct localized headings reported as missing`);
    assert.ok(
      !result.issues.some(i => i.severity === 'critical'),
      `${lang}: unexpected critical issues: ${JSON.stringify(result.issues, null, 2)}`,
    );
    assert.ok(
      result.score >= DEFAULT_MIN_SCORE,
      `${lang}: scored ${result.score}, below the ${DEFAULT_MIN_SCORE} threshold`,
    );
    assert.ok(isPass(result, DEFAULT_MIN_SCORE), `${lang}: a CV the tool generated must pass its own ATS check`);
  });
}

test('verify-ats still reports genuinely missing headings in a non-English CV', () => {
  // The wide net must not become a rubber stamp: recognising German headings
  // cannot mean every German document has every section. Same markup, real
  // German headings, but no education and no skills section.
  const html = `<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"></head><body>
    <div class="header"><h1>Andrea Hoffmann</h1>
      <div class="contact-row">andrea@example.de | +49 151 2345 6789</div></div>
    <div class="section"><div class="section-title">Berufserfahrung</div>
      <p>Leitung der Betriebsorganisation eines internationalen Logistikdienstleisters mit
      Verantwortung für Planung, Steuerung und die kontinuierliche Verbesserung sämtlicher
      operativer Abläufe an mehreren europäischen Standorten über viele Jahre hinweg.</p></div>
  </body></html>`;
  const result = auditAts(html);
  const missing = result.issues.find(i => /Missing standard section heading/.test(i.message));
  assert.ok(missing, 'a German CV with no Ausbildung and no Kenntnisse must still be flagged');
  // Only the LIST is asserted, not the whole message: the advisory sentence
  // that follows it names all three sections every time.
  const named = missing.message.match(/heading\(s\): ([^.]+)\./)[1].split(', ');
  assert.deepEqual(named.sort(), ['Education', 'Skills'], 'Berufserfahrung must be recognised');
});

test('verify-ats does not invent a font or an image from the shipped template', () => {
  // Two language-independent parse bugs that surfaced alongside the i18n ones
  // and hit every CV, English included:
  //   - `font-family: var(--font-family, …)` was comma-split into a font named
  //     "var(--font-family", reported as non-standard, costing all 10 font
  //     points on every generated CV;
  //   - the template documents its optional profile photo in a CSS comment
  //     containing the literal text "<img>", which the image scan counted as a
  //     real content image.
  const html = buildCv('de');
  assert.ok(
    html.includes('var(--font-family)'),
    'fixture regression: the template no longer uses var(--font-family), so this proves nothing',
  );

  const result = auditAts(html);
  assert.ok(
    !result.issues.some(i => /var\(--/.test(i.message)),
    `a CSS custom-property reference is not a font name: ${JSON.stringify(result.issues)}`,
  );
  assert.ok(
    !result.issues.some(i => /image/i.test(i.message)),
    `no image is present in the rendered CV: ${JSON.stringify(result.issues)}`,
  );
});

test('verify-ats still flags a genuinely non-standard font', () => {
  const html = buildCv('de').replace(
    /--font-family:[^;]+;/,
    "--font-family: 'Comic Sans MS', cursive;",
  );
  const result = auditAts(html);
  assert.ok(
    result.issues.some(i => /comic sans ms/i.test(i.message)),
    'the var() fix must not blind the font check to the fallback stack it names',
  );
});

// ── verify-cv-facts ──────────────────────────────────────────────────

for (const [lang, expected, inflate] of [
  [
    'de',
    ['12 countries', '15 years', '18%', '22 employees', '3 sites', '40 customers', '6 managers', '9 months'],
    ['22 Mitarbeitenden', '82 Mitarbeitenden'],
  ],
  [
    'ja',
    ['12 countries', '15 years', '18%', '40 customers', '45 employees', '6 managers', '9 months'],
    ['45名の従業員', '85名の従業員'],
  ],
  [
    'ar',
    ['12 countries', '15 years', '18%', '22 employees', '3 sites', '40 customers', '6 managers', '9 months'],
    ['٢٢ موظفا', '٨٢ موظفا'],
  ],
]) {
  test(`verify-cv-facts actually checks the counts in a ${lang} CV`, () => {
    const html = buildCv(lang);

    // The bug was a gate that verified nothing and said so only in a warning.
    // Assert the claims are really extracted, not just that the verdict is green.
    const claims = [...metricClaims(html)].sort();
    for (const claim of expected) {
      assert.ok(claims.includes(claim), `${lang}: expected claim ${claim}; got ${JSON.stringify(claims)}`);
    }

    const truthful = factsFor(html, lang);
    assert.equal(
      truthful.verdict,
      'pass',
      `${lang}: a truthful CV must pass — ${JSON.stringify({ invented: truthful.invented, coverage: truthful.coverage?.reason })}`,
    );
    assert.equal(truthful.coverage, null, `${lang}: nothing should be reported as unread`);
  });

  test(`verify-cv-facts blocks an inflated count in a ${lang} CV`, () => {
    // The half that matters. Before the lexicon this edit changed nothing: the
    // number was invisible either way, so the gate passed the fabrication.
    const [from, to] = inflate;
    const html = buildCv(lang);
    assert.ok(html.includes(from), `fixture regression: ${from} is not in the generated HTML`);

    const result = factsFor(html.replace(from, to), lang);
    assert.equal(result.verdict, 'block', `${lang}: an inflated headcount must block`);
    assert.ok(
      result.invented.some(claim => /^(?:82|85) /.test(claim)),
      `${lang}: expected the inflated figure among ${JSON.stringify(result.invented)}`,
    );
  });
}

test('a CJK CV\'s dates are not read as durations', () => {
  // 2019年4月 / 2024年3月 / 2009年 all appear in the Japanese fixtures. In ja/zh/ko
  // a date has exactly the shape of a count claim, so without the calendar-year
  // guard every dated CJK CV would fail on fabricated "2024 years" claims.
  const html = buildCv('ja');
  const claims = [...metricClaims(html)];
  const yearClaims = claims.filter(c => c.endsWith(' years'));
  assert.deepEqual(yearClaims, ['15 years'], `only the real duration should count: ${JSON.stringify(claims)}`);
  assert.ok(
    !claims.some(c => /^20\d\d /.test(c)),
    `a calendar year became a claim: ${JSON.stringify(claims)}`,
  );
});

// ── the lexicon's own invariants ─────────────────────────────────────

test('every metric-noun canonical is a real English metric noun', () => {
  // This is what makes the tables safe to widen. A foreign form whose canonical
  // has no English counterpart would produce claims that can never match an
  // English cv.md, so a truthful CV would fail the gate — the same bug class,
  // arriving from the opposite direction. Read from the source rather than
  // re-listed here, so the two cannot drift.
  const src = readFileSync(join(ROOT, 'verify-cv-facts.mjs'), 'utf-8');
  const block = src.match(/const METRIC_NOUNS = \[([\s\S]*?)\n\];/);
  assert.ok(block, 'could not locate METRIC_NOUNS in verify-cv-facts.mjs');
  const english = new Set([...block[1].matchAll(/'([a-z]+)'/g)].map(m => m[1]));

  for (const canonical of Object.keys(METRIC_NOUN_FORMS)) {
    assert.ok(
      english.has(canonical),
      `"${canonical}" is a lexicon canonical but not an English METRIC_NOUNS entry`,
    );
  }
});

test('the lexicon covers every language that ships a mode set', () => {
  // modes/ is the repo's own definition of a supported market. A language with
  // a mode set but no noun forms is a CV the gate silently cannot read.
  for (const lang of SUPPORTED_LANGUAGES) {
    if (lang === 'en') continue; // English lives in verify-cv-facts.mjs itself
    const concepts = Object.entries(METRIC_NOUN_FORMS)
      .filter(([, byLang]) => (byLang[lang] || []).length > 0)
      .map(([concept]) => concept);
    assert.ok(
      concepts.length >= 10,
      `${lang}: only ${concepts.length} metric concepts have forms — a CV in this language is barely checked`,
    );
    for (const required of ['years', 'employees', 'projects']) {
      assert.ok(
        concepts.includes(required),
        `${lang}: no "${required}" forms, the most commonly counted thing on a CV`,
      );
    }
  }
});

test('no surface form maps to two different concepts', () => {
  // metricNounIndex() resolves a duplicate first-wins, which is fine for a form
  // two languages spell the same way for the SAME concept ("teams", "clients")
  // and silently wrong for one they do not. Detected here rather than debugged
  // later out of a mis-attributed claim.
  const seen = new Map();
  const conflicts = [];
  for (const [canonical, byLang] of Object.entries(METRIC_NOUN_FORMS)) {
    for (const [lang, forms] of Object.entries(byLang)) {
      for (const form of forms) {
        const key = form.toLowerCase();
        const prior = seen.get(key);
        if (prior && prior.canonical !== canonical) {
          conflicts.push(`"${form}" is ${prior.canonical} (${prior.lang}) and ${canonical} (${lang})`);
        } else if (!prior) {
          seen.set(key, { canonical, lang });
        }
      }
    }
  }
  assert.deepEqual(conflicts, []);
  assert.ok(metricNounIndex().size >= 500, 'sanity: the derived index is populated');
});
