import { NextResponse } from "next/server";
import fs from "node:fs";
import path from "node:path";
import { careerOpsRoot } from "@/lib/career-ops";

export const dynamic = "force-dynamic";

// One-time seed from the user's Claude tracker CSV data
export async function POST() {
  const file = path.join(careerOpsRoot(), "data", "internships.json");

  // Don't overwrite if already seeded
  try {
    fs.accessSync(file);
    const existing = JSON.parse(fs.readFileSync(file, "utf8"));
    if (existing.length > 0) {
      return NextResponse.json({ message: "already seeded", count: existing.length });
    }
  } catch {
    // no file yet, proceed
  }

  const data = SEED_DATA.map((row) => ({
    id: crypto.randomUUID(),
    ...row,
    statusLog: [],
  }));

  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(data, null, 2));

  return NextResponse.json({ imported: data.length });
}

const SEED_DATA = [
  { company: "Airbnb", role: "Data Science Intern (Analytics / Inference tracks)", location: "", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Airbnb DS row appeared when the Simplify Summer 2027 repo was filtered for target companies. Check the careers page directly, and confirm whether a posting is the Analytics or Inference track before preparing.", lastVerified: "2026-10-01" },
  { company: "Amazon", role: "2027 Data Science Internship - United States", location: "United States", status: "closed" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Live, and explicitly PhD/Masters in the requisition title - you are not eligible. Amazon's undergraduate-accessible data roles are BIE and BA, and neither has posted.", gradEligibility: "PhD or Master's student", lastVerified: "2026-10-01", source: "posting" },
  { company: "Amazon", role: "Business Analyst Internship (US)", location: "", status: "not_posted" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No US BA internship for 2027 on amazon.jobs today. Same picture as Sept 12.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Amazon", role: "Business Intelligence Engineer Internship (US)", location: "Prior cycle: Seattle area, Bay Area, DMV, Austin, NYC, Minneapolis", status: "not_posted" as const, track: "BIE", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Searched amazon.jobs directly today: the only BI internship returned is a 6-month Luxembourg role. Still nothing in the US for 2027. Treat the BIE track as speculative for this cycle.", requirements: "SQL querying and modeling; schema definition languages; analytics visualization tools; 40 hrs/week.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Amazon", role: "Software Development Engineer Intern - Summer 2027", location: "Seattle, WA; Vancouver BC; Toronto ON", status: "wishlist" as const, track: "SWE", term: "Summer 2027", dateAdded: "2026-10-01", notes: "The Simplify repo lists Amazon SDE Summer 2027 reqs as active, but a direct amazon.jobs search returned no rows today. Check amazon.jobs yourself. This is the secondary track.", requirements: "Online assessment: two coding problems, debugging section, Work Simulation and Work Styles questionnaire.", dateConfidence: "Reported", lastVerified: "2026-10-01", source: "posting" },
  { company: "American Express", role: "Campus Undergraduate Summer Internship - 2027 Data Analytics, Enterprise Technology Services", location: "Was Charlotte NC, Phoenix AZ, Palo Alto CA, New York NY", status: "closed" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-09-01", notes: "These four reqs had a reported Oct 1 deadline last run. They no longer appear among the 8 live Campus Undergraduate Summer 2027 postings on Amex's board.", dateConfidence: "Reported", lastVerified: "2026-10-01", source: "posting" },
  { company: "American Express", role: "Campus Undergraduate Summer Internship - 2027 Data Analytics, Global Servicing", location: "New York, NY (hybrid)", status: "wishlist" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-08-18", deadline: "2026-10-01", notes: "APPLY TODAY. 'Apply Before 10/01/2026, 08:55 PM'. Financial Crimes Risk & Controls team. $24.05-$63/hr plus sign-on bonus.", requirements: "SQL, Python, data analysis/visualization tools; translating findings into recommendations.", dateConfidence: "Confirmed", workAuth: "US work eligibility required; no visa sponsorship", gradEligibility: "Bachelor's candidate, expected graduation December 2027 - June 2028", lastVerified: "2026-10-01", source: "posting" },
  { company: "American Express", role: "Campus Undergraduate Summer Internship - 2027 Data Engineer, Enterprise Technology Services", location: "Sunrise, FL", status: "wishlist" as const, track: "BIE", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-08-31", deadline: "2026-10-29", notes: "Four weeks of runway. Closest to the Amazon BIE prep. Florida location.", dateConfidence: "Confirmed", workAuth: "No visa sponsorship", gradEligibility: "Expected graduation between December 2027 and June 2028", lastVerified: "2026-10-01", source: "posting" },
  { company: "American Express", role: "Campus Undergraduate Summer Internship - 2027 Strategy & Analytics, Credit & Fraud Risk", location: "New York, NY; Phoenix, AZ", status: "closed" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-08-03", notes: "Amex's own page now returns 'This job is no longer available.'", dateConfidence: "Confirmed", lastVerified: "2026-10-01", source: "posting" },
  { company: "American Express", role: "Data Science Intern - Global Decision Science, Credit & Fraud Risk", location: "New York, NY", status: "closed" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Listed in Simplify repo with advanced-degree marker (Master's/PhD/MBA required). Not eligible as an undergraduate.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Apple", role: "Data Science / Software Engineering Internship", location: "", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Not re-verified. Apple posts team by team with no universal open date; reported to open around September.", lastVerified: "2026-10-01" },
  { company: "Bank of America", role: "Quantitative Data Analytics Summer Analyst Program - 2027", location: "US", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Appeared repeatedly on a daily DA feed through late Aug and early Sept but was not re-verified today. Verify on the BofA campus site.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Capital One", role: "Business Analyst Intern - Summer 2027 (Analyst Intern Program)", location: "Was McLean VA, Richmond VA, Chicago IL, New York NY, Plano TX", status: "closed" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-08-12", notes: "Gone. Capital One's internship-programs page now shows only a job-alert signup under Business Analytics. Was flagged as the highest-value open item.", dateConfidence: "Confirmed", workAuth: "No sponsorship of any kind", lastVerified: "2026-10-01", source: "posting" },
  { company: "Capital One", role: "Current Master's / PhD Internship Programs - Summer 2027", location: "San Jose, CA and others", status: "closed" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "What remains of Capital One's Summer 2027 intern cycle: 5 postings, all MBA, PhD or Master's. Listed only to document that the undergraduate door is shut.", workAuth: "No sponsorship", lastVerified: "2026-10-01", source: "posting" },
  { company: "Capital One", role: "Data Analyst Intern - Summer 2027", location: "Was McLean, VA; Richmond, VA", status: "closed" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Capital One is effectively done with undergraduate analyst internships for this cycle.", workAuth: "No sponsorship of any kind", lastVerified: "2026-10-01", source: "posting" },
  { company: "Chewy", role: "BIE / Analytics Intern", location: "", status: "unknown" as const, track: "BIE", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Chewy row in the Simplify repo filter. With Amazon BIE unposted, Chewy and the Amex Data Engineer req are where BIE prep can go.", lastVerified: "2026-10-01" },
  { company: "Databricks", role: "Summer 2027 Internships (DS / SWE tracks)", location: "San Francisco, CA; Mountain View, CA; Bellevue, WA", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Not re-verified. The graduation band seen in August (Fall 2027 or Spring 2028) would exclude a June 2028 graduation - confirm before spending time.", gradEligibility: "Graduating Fall 2027 or Spring 2028", workAuth: "Sponsors CPT for US interns (reported)", lastVerified: "2026-10-01" },
  { company: "Deloitte", role: "Analytics / Consulting Client Service Internship", location: "", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Not re-verified. Sources still conflict on whether the Aug-Sept window is the Summer 2027 or Summer 2028 cycle. Resolve on apply.deloitte.com.", lastVerified: "2026-10-01" },
  { company: "Discover", role: "Data Analytics Intern", location: "", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Discover row in the Simplify repo filter. Worth a direct check now that Capital One is gone.", lastVerified: "2026-10-01" },
  { company: "DoorDash", role: "Data Science / Analytics Intern", location: "San Francisco, Seattle, New York, LA on prior cycles", status: "not_posted" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "DoorDash's university-careers page lists live Summer 2027 roles but no data science or analytics track. The reported Aug-Sept window has passed without a DS posting.", dateConfidence: "Confirmed", lastVerified: "2026-10-01", source: "posting" },
  { company: "DoorDash", role: "Software Engineer, Intern (Summer 2027) - US", location: "US (SF, Seattle, NYC, LA)", status: "wishlist" as const, track: "SWE", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Live on DoorDash's own page. Rolling, and community guidance is that most interview slots are gone by late fall. Secondary track.", requirements: "Pursuing BS or MS in CS; databases and SQL; algorithms and data structures; one object-oriented language.", dateConfidence: "Confirmed", workAuth: "F-1 with CPT accepted; J-1 not supported", lastVerified: "2026-10-01", source: "posting" },
  { company: "Goldman Sachs", role: "2027 Summer Analyst Program, Americas", location: "Americas", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Still not re-verified. The Aug 15, 2026 open date has long passed, so this is either deep into rolling review or closed. Maximum 4 division/location combinations per recruiting year.", lastVerified: "2026-10-01" },
  { company: "Google", role: "Business / Data Analytics Intern (gTech, Business Data Science) and STEP", location: "", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Still no 2027 business or data analytics requisition found. STEP was reported as expected Sept-Oct. Worth a weekly check through October.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Google", role: "Software Engineering Intern, Summer 2027 (BS/MS)", location: "Multiple US locations", status: "unknown" as const, track: "SWE", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Not re-verified. Reported live in August after the earlier window closed July 24. Google windows run 2-4 weeks and close when projects fill. Have the transcript ready.", requirements: "Coding in two or more general-purpose languages; data structures and algorithms. Resume and current transcript required.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Instacart", role: "Data Science Intern", location: "", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Instacart row in the Simplify repo filter. Take-home heavy. Still a gap across three runs.", lastVerified: "2026-10-01" },
  { company: "JPMorganChase", role: "2027 Corporate Analyst Development Program - Summer Analyst", location: "Chicago, IL", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", deadline: "2026-10-03", notes: "Two days out on an aggregator-reported deadline. Budget for the HireVue immediately rather than submitting and stalling.", requirements: "Analytical and problem-solving skills; translating data into actionable insights. A HireVue is required.", dateConfidence: "Reported", workAuth: "Must be authorized to work in the US; no immigration sponsorship offered", lastVerified: "2026-10-01", source: "posting" },
  { company: "JPMorganChase", role: "Focused Analytics Solutions Team (FAST) Program - Summer Analyst", location: "US", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-08-26", notes: "Unresolved. One guide says JPMorgan's 2027 Data & Analytics program already closed; a daily feed listed FAST as newly posted in late August. Check the careers site.", workAuth: "No OPT or CPT support reported", lastVerified: "2026-10-01", source: "posting" },
  { company: "LinkedIn", role: "Data Science Intern", location: "", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No LinkedIn DS row in the Simplify repo filter. Third run without a direct check.", lastVerified: "2026-10-01" },
  { company: "Mastercard", role: "Data Scientist Intern, Summer 2027", location: "St. Louis, MO", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-08-30", notes: "Not re-verified. A titled DS intern role in payments. Decide whether you would actually take St. Louis before spending the effort.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Meta", role: "Data Scientist Intern, Product Analytics", location: "New York, NY", status: "unknown" as const, track: "DS", term: "Unknown", dateAdded: "2026-10-01", notes: "Unchanged from Sept 12: requisition is live and BS/MS eligible, but the title carries no term and the page states no dates. Ask a recruiter which cycle it is. The PhD variant is separate.", requirements: "In the process of obtaining a Bachelor's and/or Master's in Mathematics, Statistics or a relevant technical field. SQL, Python, R.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Microsoft", role: "Data Science: Internship Opportunities - Redmond", location: "Redmond, WA", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-09-02", notes: "Could not re-verify on Microsoft's own board today. The Sept 2 posting date and rolling language are from a job-board mirror. Status downgraded to Unknown. This is the strongest undergraduate-eligible big-tech DS lead you have.", requirements: "Machine learning, statistics, experiments and AI applied to products. $5,690-$11,210/month band.", dateConfidence: "Reported", lastVerified: "2026-10-01", source: "posting" },
  { company: "Netflix", role: "Data Science / Analytics Engineering Intern", location: "", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Not researched individually. Reported to run a very small program.", lastVerified: "2026-10-01" },
  { company: "Pinterest", role: "Data Science Intern", location: "", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Pinterest DS row in the Simplify repo filter. Check the careers page directly.", lastVerified: "2026-10-01" },
  { company: "Qualcomm", role: "Data Analyst / IT / Engineering Internship", location: "San Diego, CA; Santa Clara; Irvine; Austin", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Not re-verified. San Diego HQ makes this the most convenient on-site option you have. Check careers.qualcomm.com directly.", requirements: "SQL, statistics, Python, R, Tableau, predictive modeling; available 11-14 weeks.", lastVerified: "2026-10-01" },
  { company: "Reddit", role: "Data Science Intern", location: "San Francisco, CA; New York, NY on prior cycles", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Reddit DS row in the Simplify repo filter. Prior cycles ran DS intern roles including an Ads track, some routed through RippleMatch.", workAuth: "Sponsorship not available on prior-cycle DS intern postings", lastVerified: "2026-10-01" },
  { company: "Robinhood", role: "Data Science Intern (Summer 2027)", location: "Menlo Park, CA (in person 3+ days/week)", status: "closed" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-09-29", notes: "Newly posted Sept 29 and graduate-only, so you are not eligible. Robinhood can come off the active list.", gradEligibility: "Full-time GRADUATE degree program", lastVerified: "2026-10-01", source: "posting" },
  { company: "Snap", role: "Data Science Intern", location: "Santa Monica / Los Angeles area", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Snap DS row in the Simplify repo filter. LA-based and commutable, so worth a direct check.", lastVerified: "2026-10-01" },
  { company: "Sports analytics boards", role: "League / team analytics internships", location: "Various", status: "not_posted" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "These typically open November through February. Your Floor Generals passing-network work is the strongest portfolio match. Put a November reminder on the boards.", lastVerified: "2026-10-01" },
  { company: "Spotify", role: "Summer Internship, Data Science / Data Analytics (US)", location: "New York, NY on prior cycles", status: "not_posted" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Reported pattern is a hard-deadline window opening mid-to-late January 2027. Set a January reminder rather than checking weekly.", dateConfidence: "Reported", lastVerified: "2026-10-01", source: "posting" },
  { company: "Stripe", role: "Data Science / Analytics Intern", location: "Seattle, WA", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "The Simplify repo shows a live Stripe SWE Intern req but no data science or analytics row. Take-home heavy if one appears.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Target", role: "Data Science / Data Analyst Intern", location: "Minneapolis, MN", status: "unknown" as const, track: "DA", term: "Summer 2027", dateAdded: "2026-10-01", notes: "No Target row in the Simplify repo filter. Walmart's 2027 cycle is confirmed underway, so Target's may be too. Check directly.", lastVerified: "2026-10-01" },
  { company: "TikTok", role: "Data Engineer Intern, Monetization Data - Summer 2027", location: "San Jose, CA (in person)", status: "wishlist" as const, track: "BIE", term: "Summer 2027", dateAdded: "2026-10-01", opened: "2026-08-10", notes: "Carried from Sept 12. Undergraduate-eligible and maps onto SQL, data-modeling and ETL prep. With Amazon BIE unposted, this is one of the few places that prep can go.", requirements: "SQL with relational and non-relational databases; Python, Java or Go; data modeling, warehousing, ETL/ELT. Spark, Kafka, BigQuery, Databricks, Snowflake.", dateConfidence: "Reported", lastVerified: "2026-10-01", source: "posting" },
  { company: "TikTok / ByteDance", role: "Data Scientist Intern - 2027 Summer (BS/MS)", location: "San Jose, CA; Seattle, WA", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Filtering the Simplify repo returns almost entirely SWE and PM roles — no US DS requisition surfaced. Two-application global cap per Jan-Jun / Jul-Dec window still applies.", requirements: "Metrics definition, root cause analysis, experimentation methodology; SQL plus Python or R.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Uber", role: "Data Science Intern, US", location: "San Francisco, CA; Sunnyvale, CA on prior cycles", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Not re-verified; no 2027 requisition found last run. Uber runs a talent-registration flow for DS internships - registering costs nothing and gets you notified. Do that this week.", requirements: "SQL, Python and A/B testing.", lastVerified: "2026-10-01", source: "posting" },
  { company: "Walmart", role: "Data Science / Data Analyst Intern (Global Tech)", location: "Bentonville, AR; Hoboken, NJ and others", status: "unknown" as const, track: "DS", term: "Summer 2027", dateAdded: "2026-10-01", notes: "Walmart's Summer 2027 corporate intern cycle is confirmed underway. Their search page would not render keyword results through the browser. The reported pattern has most interview slots filled by mid-September, which has passed.", workAuth: "No visa sponsorship reported; CPT/OPT accepted", lastVerified: "2026-10-01", source: "posting" },
];
