import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { classifyFocusAreas, discoverRoleResumes, isSafeRoleSlug, nextRoleVersion, parseApprovedRoleResumeInput, planRoleResume, reserveRoleResumeDirectory, roleResumePaths, slugifyRole, validateApprovedRoleResumePlan, validateRoleResumePlanShape } from "../../src/lib/role-resumes.mjs";

function root() { const dir = fs.mkdtempSync(path.join(os.tmpdir(), "co-role-")); fs.mkdirSync(path.join(dir, "output")); fs.writeFileSync(path.join(dir, "cv.md"), "Java REST APIs Docker and Kubernetes production troubleshooting", "utf8"); return dir; }
test("general role slug generation", () => assert.equal(slugifyRole("Application Developer"), "application-developer"));
test("v001 creation and version increment", () => { const r = root(); assert.equal(nextRoleVersion(r, "application-developer"), "v001"); fs.mkdirSync(path.join(r, "output", "role-resumes", "application-developer", "v001"), { recursive: true }); assert.equal(nextRoleVersion(r, "application-developer"), "v002"); });
test("unsupported focus areas are rejected", () => { const result = classifyFocusAreas("Java and REST APIs", ["Java", "Terraform"]); assert.deepEqual(result, { supported: ["Java"], unsupported: ["Terraform"] }); });
test("plan uses the canonical focus-area contract", () => { const plan = planRoleResume(root(), { targetRole: "Application Developer", focusAreas: ["Java", "REST APIs", "AWS"] }); assert.equal(plan.roleSlug, "application-developer"); assert.deepEqual(plan.supportedFocusAreas, ["Java", "REST APIs"]); assert.deepEqual(plan.unsupportedFocusAreas, ["AWS"]); });
test("role-resume discovery resolves latest", () => { const r = root(); for (const version of ["v001", "v002"]) { const d = path.join(r, "output", "role-resumes", "application-developer", version); fs.mkdirSync(d, { recursive: true }); fs.writeFileSync(path.join(d, "cv.pdf"), "pdf"); fs.writeFileSync(path.join(d, "metadata.json"), JSON.stringify({ targetRole: "Application Developer", factGate: "passed" })); } const found = discoverRoleResumes(r); assert.equal(found[0].latest.version, "v002"); });
test("role paths reject traversal", () => { assert.equal(isSafeRoleSlug("../secret"), false); assert.throws(() => roleResumePaths(root(), { roleSlug: "../secret", version: "v001" })); });
test("prior versions cannot be overwritten", () => { const paths = roleResumePaths(root(), { roleSlug: "application-developer", version: "v001" }); reserveRoleResumeDirectory(paths); assert.throws(() => reserveRoleResumeDirectory(paths), { code: "EEXIST" }); });
test("approved plan reaches generation validation intact", () => { const r = root(); const plan = planRoleResume(r, { targetRole: "Application Developer", focusAreas: ["Java", "REST APIs"] }); assert.deepEqual(validateApprovedRoleResumePlan(r, { ...plan, approved: true }), plan); });
test("empty supportedFocusAreas is valid", () => { const value = { targetRole: "Application Developer", roleSlug: "application-developer", positioning: "Senior Application Developer / Software Engineer", supportedFocusAreas: [], unsupportedFocusAreas: ["AWS"], version: "v001" }; assert.deepEqual(validateRoleResumePlanShape(value).supportedFocusAreas, []); });
test("missing supportedFocusAreas fails with a controlled contract error", () => { assert.throws(() => validateRoleResumePlanShape({ targetRole: "Application Developer", roleSlug: "application-developer", positioning: "Senior Application Developer / Software Engineer", unsupportedFocusAreas: [], version: "v001" }), /supportedFocusAreas.*array of strings/); });
test("malformed run input is controlled before prompt generation", () => { const r = root(); assert.throws(() => parseApprovedRoleResumeInput(r, "{bad"), /must be valid JSON/); const incomplete = JSON.stringify({ targetRole: "Application Developer", roleSlug: "application-developer", positioning: "Senior Application Developer \/ Software Engineer", unsupportedFocusAreas: [], version: "v001", approved: true }); assert.throws(() => parseApprovedRoleResumeInput(r, incomplete), /supportedFocusAreas.*array of strings/); });
