import type { ATSAnalysisResult } from './types.ts';
import { generateAIPrompt } from './promptGenerator.ts';

export function generateMarkdownAuditReport(result: ATSAnalysisResult): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const formattedSize = result.fileSize < 1024 * 1024 
    ? (result.fileSize / 1024).toFixed(1) + ' KB' 
    : (result.fileSize / (1024 * 1024)).toFixed(1) + ' MB';

  let md = `# GigpilotAIScore – ATS Resume Compatibility Audit Report

**Report Date:** ${dateStr}  
**Resume File:** \`${result.fileName}\` (${formattedSize})  
**Analysis Mode:** ${result.hasJobDescription ? 'Targeted Job Match' : 'General ATS Compatibility Scan'}  
**Target Role:** ${result.keywords.targetRole || 'General ATS Fit'}  

---

## 📊 Overall ATS Score: ${result.totalScore} / 100
**Category:** ${result.scoreCategory}  
**Summary:** ${result.scoreExplanation}

---

## 📈 Score Breakdown
| Category | Score | Max | Status | Feedback |
| :--- | :---: | :---: | :---: | :--- |
`;

  for (const item of result.breakdown) {
    md += `| ${item.category} | ${item.score} | ${item.maxScore} | **${item.status}** | ${item.explanation} |\n`;
  }

  md += `\n---\n\n## 🎯 Keyword Alignment & Match\n`;
  md += `- **Match Score:** ${result.keywords.score}% Match\n`;
  md += `- **Role Alignment:** ${result.keywords.roleAlignment}\n`;
  md += `- **Matched Keywords (${result.keywords.matchedKeywords.length}):** ${result.keywords.matchedKeywords.length > 0 ? result.keywords.matchedKeywords.join(', ') : 'None extracted'}\n`;
  md += `- **Missing Keywords (${result.keywords.missingKeywords.length}):** ${result.keywords.missingKeywords.length > 0 ? result.keywords.missingKeywords.join(', ') : 'None'}\n`;
  if (result.keywords.overusedKeywords && result.keywords.overusedKeywords.length > 0) {
    md += `- **Overused Keywords:** ${result.keywords.overusedKeywords.join(', ')}\n`;
  }

  md += `\n---\n\n## 📋 Structure & Contact Information\n`;
  md += `### Contact Details Detected:\n`;
  const c = result.contactInfo;
  md += `- **Full Name:** ${c.name || 'Not detected'}\n`;
  md += `- **Email:** ${c.email || 'Not detected'}\n`;
  md += `- **Phone:** ${c.phone || 'Not detected'}\n`;
  md += `- **Location:** ${c.location || 'Not detected'}\n`;
  md += `- **LinkedIn:** ${c.linkedIn || 'Not detected'}\n`;
  md += `- **GitHub:** ${c.github || 'Not detected'}\n`;
  md += `- **Website/Portfolio:** ${c.website || c.portfolio || 'Not detected'}\n`;

  md += `\n### Section Headings Detected:\n`;
  md += `| Section Name | Status | Standard Heading Used |\n| :--- | :--- | :--- |\n`;
  for (const s of result.sections) {
    const status = s.found ? '✓ Detected' : s.isOptional ? '• Optional (Missing)' : '✕ Missing';
    md += `| ${s.name} | ${status} | ${s.detectedHeading || 'N/A'} |\n`;
  }

  md += `\n---\n\n## ⚠️ Formatting Risks & Parsing Issues\n`;
  if (result.formatting.length === 0) {
    md += `✓ No major formatting risks detected.\n`;
  } else {
    for (const f of result.formatting) {
      md += `- **[${f.type.toUpperCase()}] ${f.title}:** ${f.description} *(Impact: ${f.impact})*\n`;
    }
  }

  md += `\n---\n\n## 💡 Top Actionable Recommendations\n`;
  for (let i = 0; i < result.recommendations.length; i++) {
    const r = result.recommendations[i];
    md += `${i + 1}. **[${r.priority.toUpperCase()} PRIORITY] ${r.title}:** ${r.description}\n`;
  }

  md += `\n---\n\n## 🤖 Auto-Generated AI Resume Fix Prompt\n`;
  md += `\`\`\`text\n${generateAIPrompt(result, 'full')}\n\`\`\`\n`;

  md += `\n---\n\n## 📄 Extracted Resume Text\n`;
  md += `\`\`\`text\n${result.extractedText || 'No text extracted.'}\n\`\`\`\n`;

  md += `\n---\n*Report generated by GigpilotAIScore – 100% Free & Client-Side ATS Resume Checker.*\n`;

  return md;
}
