"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Award, Brain, BriefcaseBusiness, FolderKanban, GraduationCap } from "lucide-react";
import { Button } from "@/components/ui/button";

type Kind = "certification" | "skill" | "project" | "work" | "education";
type WorkEntry = { index: number; label: string };
const actions: { kind: Kind; title: string; icon: typeof Award }[] = [
  { kind: "certification", title: "Add Certification", icon: Award }, { kind: "skill", title: "Add Skill", icon: Brain },
  { kind: "project", title: "Add Project Experience", icon: FolderKanban }, { kind: "work", title: "Update Work Experience", icon: BriefcaseBusiness },
  { kind: "education", title: "Update Education", icon: GraduationCap },
];
const split = (value: string) => value.split(/[\n,]/).map((v) => v.trim()).filter(Boolean);
const base = { certification: { name: "", organization: "", dateEarned: "", expirationDate: "", credentialId: "", credentialUrl: "", relatedSkills: "", notes: "" }, skill: { name: "", category: "", experienceSource: "Professional work", professionalUse: false, whereUsed: "", years: "", notes: "", experienceIndex: "" }, project: { name: "", projectType: "Professional", organization: "", role: "", startDate: "", endDate: "", present: false, description: "", technologies: "", responsibilities: "", achievements: "", metrics: "", url: "" }, work: { experienceIndex: "", changeType: "responsibility", value: "" }, education: { entryType: "degree", degree: "", school: "", graduationYear: "", coursework: "", program: "" } };
const inputClass = "mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground";

export function ProfileUpdateView() {
  const [kind, setKind] = useState<Kind | null>(null); const [form, setForm] = useState<Record<string, any>>({});
  const [workEntries, setWorkEntries] = useState<WorkEntry[]>([]); const [preview, setPreview] = useState<any>(null); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [confirmDuplicate, setConfirmDuplicate] = useState(false);
  useEffect(() => { fetch("/api/profile-update/preview").then((r) => r.json()).then((v) => setWorkEntries(v.workEntries || [])).catch(() => {}); }, []);
  const choose = (next: Kind) => { setKind(next); setForm({ ...base[next] }); setPreview(null); setError(""); setSaved(false); };
  const set = (key: string, value: any) => setForm((old) => ({ ...old, [key]: value }));
  const label = (text: string, key: string, required = false, type = "text") => <label className="text-sm text-muted">{text}{required && " *"}<input type={type} value={form[key] || ""} onChange={(e) => set(key, e.target.value)} className={inputClass} /></label>;
  const area = (text: string, key: string) => <label className="text-sm text-muted">{text}<textarea value={form[key] || ""} onChange={(e) => set(key, e.target.value)} className={`${inputClass} min-h-20`} /></label>;
  const select = (text: string, key: string, options: string[]) => <label className="text-sm text-muted">{text}<select value={form[key] || options[0]} onChange={(e) => set(key, e.target.value)} className={inputClass}>{options.map((v) => <option key={v} value={v}>{v}</option>)}</select></label>;
  const workSelect = () => <label className="text-sm text-muted">Existing job *<select value={form.experienceIndex} onChange={(e) => set("experienceIndex", Number(e.target.value))} className={inputClass}><option value="">Select a job</option>{workEntries.map((v) => <option key={v.index} value={v.index}>{v.label}</option>)}</select></label>;
  function payload() { const data = { ...form }; for (const key of ["relatedSkills", "technologies", "responsibilities", "achievements", "coursework"]) if (key in data) data[key] = split(data[key]); if (data.experienceIndex === "") delete data.experienceIndex; return { updateType: kind, data }; }
  async function prepare() { setError(""); const r = await fetch("/api/profile-update/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); const b = await r.json(); if (!r.ok) setError(b.error); else { setPreview(b); setConfirmDuplicate(false); } }
  async function apply() { const r = await fetch("/api/profile-update/apply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload(), approved: true, previewHash: preview.previewHash, confirmDuplicate }) }); const b = await r.json(); if (!r.ok) setError(b.error); else { setSaved(true); setPreview(null); } }
  return <div className="mx-auto max-w-5xl px-6 py-8"><h1 className="font-display text-2xl text-landing">Update Career Profile</h1><p className="mt-1 text-sm text-muted">Add new skills, certifications, projects, education, and work experience to your Career-Ops master profile.</p>
    <div className="mt-4 flex gap-2"><Link href="/cv" className="rounded-md border border-border bg-surface px-3 py-2 text-sm">View Master Profile</Link><Link href="/cv" className="rounded-md border border-border bg-surface px-3 py-2 text-sm">Open Advanced CV Editor</Link></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{actions.map(({ kind: value, title, icon: Icon }) => <button key={value} onClick={() => choose(value)} className="rounded-xl border border-border bg-surface p-5 text-left hover:border-brand/50"><Icon className="size-5 text-brand-text"/><span className="mt-3 block font-medium">{title}</span></button>)}</div>
    {kind && <section className="mt-6 rounded-xl border border-border bg-surface p-5"><p className="text-xs font-semibold uppercase tracking-wide text-brand-text">{preview ? "Step 2: Preview proposed change" : "Step 1: Form"}</p>{!preview ? <div className="mt-4 grid gap-4 sm:grid-cols-2">
      {kind === "certification" && <>{label("Certification name", "name", true)}{label("Issuing organization", "organization", true)}{label("Date earned", "dateEarned", false, "date")}{label("Expiration date", "expirationDate", false, "date")}{label("Credential ID", "credentialId")}{label("Credential URL", "credentialUrl", false, "url")}{label("Related skills (comma-separated)", "relatedSkills")}{area("Notes", "notes")}</>}
      {kind === "skill" && <>{label("Skill name", "name", true)}{label("Category", "category", true)}{select("Experience source", "experienceSource", ["Professional work", "Project experience", "Certification/training", "Self-study"])}<label className="flex items-center gap-2 text-sm text-muted"><input type="checkbox" checked={!!form.professionalUse} onChange={(e) => set("professionalUse", e.target.checked)}/>Professional use</label>{form.professionalUse && workSelect()}{label("Where used", "whereUsed")}{label("Approximate years", "years", false, "number")}{area("Notes", "notes")}<p className="sm:col-span-2 text-xs text-muted">Training and self-study skills never create professional-experience claims unless Professional use is selected and an existing job is explicitly chosen.</p></>}
      {kind === "project" && <>{label("Project name", "name", true)}{select("Project type", "projectType", ["Professional", "Personal", "Client", "Open source"])}{label("Company/organization", "organization")}{label("Role", "role", true)}{label("Start date", "startDate", false, "month")}{label("End date", "endDate", false, "month")}<label className="flex items-center gap-2 text-sm text-muted"><input type="checkbox" checked={!!form.present} onChange={(e) => set("present", e.target.checked)}/>Present</label>{area("Description *", "description")}{area("Technologies", "technologies")}{area("Responsibilities", "responsibilities")}{area("Achievements/results", "achievements")}{area("Metrics", "metrics")}{label("URL", "url", false, "url")}</>}
      {kind === "work" && <>{workSelect()}{select("Change type", "changeType", ["responsibility", "technology", "project", "achievement", "quantified-result", "role-correction", "date-correction"])}{area("New value *", "value")}</>}
      {kind === "education" && <>{select("Update type", "entryType", ["degree", "training"])}{form.entryType === "degree" ? <>{label("Degree", "degree", true)}{label("School", "school", true)}{label("Graduation year", "graduationYear")}{label("Relevant coursework", "coursework")}</> : <>{label("Training/program", "program", true)}{label("School/provider", "school")}{label("Completion year", "graduationYear")}</>}</>}
      <div className="sm:col-span-2">{error && <p role="alert" className="mb-3 text-sm text-danger">{error}</p>}<Button onClick={() => void prepare()}>Preview Update</Button></div></div> : <div className="mt-4"><h2 className="font-medium">{preview.preview.section}</h2><pre className="mt-3 whitespace-pre-wrap rounded-lg border border-border bg-background p-4 text-sm">{preview.preview.markdown}</pre>{preview.warning && <div className="mt-3 text-sm text-warning">{preview.warning}<label className="mt-2 flex gap-2"><input type="checkbox" checked={confirmDuplicate} onChange={(e) => setConfirmDuplicate(e.target.checked)}/>Confirm duplicate update</label></div>}{error && <p role="alert" className="mt-3 text-sm text-danger">{error}</p>}<div className="mt-4 flex gap-2"><Button disabled={preview.duplicate && !confirmDuplicate} onClick={() => void apply()}>Approve Update</Button><Button variant="outline" onClick={() => setPreview(null)}>Edit</Button></div></div>}{saved && <p className="mt-4 text-sm text-success">Master profile updated.</p>}</section>}
  </div>;
}
