"""Recognize canonical hard skills using the reviewed Node vocabulary."""

from __future__ import annotations

import re

# Vocabulary and exact aliases copied from skill-extract.mjs for Python runtime independence.
TOKENS = ['JavaScript',
 'TypeScript',
 'Python',
 'Ruby',
 'Java',
 'Golang',
 'Rust',
 'PHP',
 'Kotlin',
 'Swift',
 'Scala',
 'Elixir',
 'C\\+\\+',
 'C#',
 '\\.NET',
 'SQL',
 'React Native',
 'React',
 'Angular',
 'Vue\\.?js',
 'Svelte',
 'Next\\.?js',
 'Django',
 'Flask',
 'FastAPI',
 'Rails',
 'Laravel',
 'Symfony',
 'Spring',
 'Node\\.?js',
 'NodeJS',
 'MongoDB',
 'MySQL',
 'PostgreSQL',
 'Postgres',
 'Redis',
 'Elasticsearch',
 'Snowflake',
 'BigQuery',
 'Databricks',
 'DynamoDB',
 'Cassandra',
 'GraphQL',
 'gRPC',
 'Kafka',
 'RabbitMQ',
 'AWS',
 'GCP',
 'Azure',
 'Docker',
 'Kubernetes',
 'k8s',
 'Terraform',
 'Ansible',
 'Helm',
 'Jenkins',
 'GitHub Actions',
 'GitLab CI',
 'CI/CD',
 'Prometheus',
 'Grafana',
 'Datadog',
 'Supabase',
 'Inngest',
 'PyTorch',
 'TensorFlow',
 'scikit-learn',
 'Pandas',
 'NumPy',
 'Spark',
 'Airflow',
 'dbt',
 'MLOps',
 'MLflow',
 'LangChain',
 'LlamaIndex',
 'Hugging Face',
 'RAG',
 'LLMs?',
 'Prompt Engineering',
 'Fine-?tuning',
 'Computer Vision',
 'NLP',
 'Tableau',
 'Power BI',
 'Looker',
 'Salesforce',
 'SAP',
 'PMI-ACP',
 'PMI ACP',
 'PgMP',
 'CAPM',
 'PMBOK',
 'PMP',
 'PRINCE2',
 'PRINCE 2',
 'Certified Scrum Product Owner',
 'Certified ScrumMaster',
 'Certified Scrum Master',
 'CSPO',
 'ITIL',
 'COBIT',
 'TOGAF',
 'Lean Six Sigma',
 'Lean Six-Sigma',
 'Six Sigma',
 'Six-Sigma',
 'CISSP',
 'CISM',
 'CIPP']
ALIASES = {'k8s': 'Kubernetes',
 'golang': 'Go',
 'postgres': 'PostgreSQL',
 'nodejs': 'Node.js',
 'node.js': 'Node.js',
 'nodejs.': 'Node.js',
 'vuejs': 'Vue.js',
 'vue.js': 'Vue.js',
 'nextjs': 'Next.js',
 'next.js': 'Next.js',
 'llm': 'LLMs',
 'llms': 'LLMs',
 'finetuning': 'Fine-tuning',
 'fine-tuning': 'Fine-tuning',
 'power bi': 'Power BI',
 'github actions': 'GitHub Actions',
 'gitlab ci': 'GitLab CI',
 'ci/cd': 'CI/CD',
 'hugging face': 'Hugging Face',
 'react native': 'React Native',
 'prompt engineering': 'Prompt Engineering',
 'computer vision': 'Computer Vision',
 'scikit-learn': 'scikit-learn',
 'c++': 'C++',
 'c#': 'C#',
 '.net': '.NET',
 'nlp': 'NLP',
 'rag': 'RAG',
 'sql': 'SQL',
 'aws': 'AWS',
 'gcp': 'GCP',
 'grpc': 'gRPC',
 'dbt': 'dbt',
 'mlops': 'MLOps',
 'mlflow': 'MLflow',
 'pmp': 'PMP',
 'pmi-acp': 'PMI-ACP',
 'pgmp': 'PgMP',
 'capm': 'CAPM',
 'pmbok': 'PMBOK',
 'prince2': 'PRINCE2',
 'cspo': 'CSPO',
 'certified scrummaster': 'Certified ScrumMaster',
 'itil': 'ITIL',
 'cobit': 'COBIT',
 'togaf': 'TOGAF',
 'lean six sigma': 'Lean Six Sigma',
 'six sigma': 'Six Sigma',
 'cissp': 'CISSP',
 'cism': 'CISM',
 'cipp': 'CIPP',
 'certified scrum master': 'Certified ScrumMaster',
 'certified scrum product owner': 'CSPO',
 'pmi acp': 'PMI-ACP',
 'prince 2': 'PRINCE2',
 'lean six-sigma': 'Lean Six Sigma',
 'six-sigma': 'Six Sigma'}
DISPLAY = {re.sub(r"[\\?]", "", token).lower(): re.sub(r"[\\?]", "", token) for token in TOKENS}
PATTERN = re.compile(r"(?<!\w)(?:" + "|".join(TOKENS) + r")(?!\w)", re.I | re.ASCII)
GO = re.compile(r"(?<!\w)Go(?![\w-])", re.ASCII)
SAFE = re.compile(r"(?<!\w)SAFe(?!\w)", re.ASCII)


def canonicalize(token: str) -> str:
    """Map exact aliases and display casing without umbrella substitutions."""
    return ALIASES.get(token.lower(), DISPLAY.get(token.lower(), token))


def extract_skills(text: str) -> set[str]:
    """Return recognized canonical skills, guarding ambiguous Go and SAFe."""
    if not text:
        return set()
    found = {canonicalize(match.group()) for match in PATTERN.finditer(text)}
    if GO.search(text):
        found.add("Go")
    if SAFE.search(text):
        found.add("SAFe")
    return found
